/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import aplikasi.config.FieldLimit;
import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.Dies;
import aplikasi.entity.Kepala;
import aplikasi.entity.Mesin;
import aplikasi.entity.Operator;
import aplikasi.entity.Trial;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.text.BadLocationException;
import repository.RepoKepala;
import repository.RepoOperator;
import repository.RepoTrial;
import services.ServiceKepala;
import services.ServiceOperator;
import services.ServiceTrial;
import view.dies.DetailDiesView;
import view.laporan.LapTrial;
import view.mesin.DetailMesinView;

/**
 *
 * @author soraya
 */
public class MainMenu extends javax.swing.JFrame {

    private final TableViewController tableController;
    private final RepoTrial repoTrial;
    private final RepoKepala repoKepala;
    private final RepoOperator repoOperator;

    private Mesin mesin;
    private Trial trial;
    private Dies dies;
    private Operator operator;
    private Kepala kepala;
    private int no = 0;
    LocalDate date;

    private List<Trial> daftarTrial = new ArrayList<>();
    private List<Kepala> daftarKepala = new ArrayList<>();
    private List<Operator> daftarOperator = new ArrayList<>();

    private FieldLimit fieldLimit;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.tableController = new TableViewController(tableView);
        this.repoTrial = new ServiceTrial(KoneksiDB.getDataSource());
        this.repoKepala = new ServiceKepala(KoneksiDB.getDataSource());
        this.repoOperator = new ServiceOperator(KoneksiDB.getDataSource());
        this.mesin = new Mesin();
        this.trial = new Trial();
        this.dies = new Dies();
        this.mesin = new Mesin();
        this.kepala = new Kepala();
        this.operator = new Operator();

        this.fieldLimit = new FieldLimit();
        ambilNoTrialTertinggi();
        refreshDataTables();
        refresDataKepala();
        refresDataOperator();
        textFieldLimit();
        setDateNowMinOne();
    }

    private void refresDataKepala() {
        try {
            txtKepala.removeAllItems();
            daftarKepala = repoKepala.findAll();
            for (Kepala k : daftarKepala) {
                txtKepala.addItem(k.getNama());
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDateNowMinOne() {
        date = LocalDate.now().minusDays(1);
        this.txtTanggal.setDate(Date.valueOf(date.toString()));
    }

    private void clearFields() {
        ambilNoTrialTertinggi();
        setDateNowMinOne();
        txtNamaDies.setText("");
        txtProses.setText("");
        txtCustomer.setText("");
        txtNamaMesin.setText("");
        refresDataKepala();
        refresDataOperator();
        txtMulai.setText("");
        txtSelesai.setText("");
        txtNoTrial.requestFocus();
    }

    private void refresDataOperator() {
        try {
            txtOperator.removeAllItems();
            daftarOperator = repoOperator.findAll();
            for (Operator k : daftarOperator) {
                txtOperator.addItem(k.getNama());
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pmnuUbah = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        btnPilihDies = new javax.swing.JButton();
        txtNamaDies = new javax.swing.JTextField();
        btnPilihMesin = new javax.swing.JButton();
        txtNamaMesin = new javax.swing.JTextField();
        txtProses = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKepala = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtOperator = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtMulai = new javax.swing.JTextField();
        txtSelesai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnPilih = new javax.swing.JButton();
        btnTanggalMin = new javax.swing.JButton();
        btnAutoNoTrial = new javax.swing.JButton();
        btnNow = new javax.swing.JButton();
        btnTanggalPlus = new javax.swing.JButton();
        txtNoTrial = new javax.swing.JTextField();
        btnNoTrialMin = new javax.swing.JButton();
        btnNoTrialPlus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuLaporan = new javax.swing.JMenu();
        mniLapTrial = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        mniTentangAplikasi = new javax.swing.JMenuItem();

        pmnuUbah.setText("Ubah");
        pmnuUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmnuUbahActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pmnuUbah);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 570));

        jLabel1.setText("No Trial");

        jLabel3.setText("Mesin");

        jLabel4.setText("Dies");

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(100, 35));
        jToolBar1.setMinimumSize(new java.awt.Dimension(100, 35));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 35));

        btnSimpan.setText("Simpan");
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(110, 35));
        btnSimpan.setMinimumSize(new java.awt.Dimension(110, 35));
        btnSimpan.setPreferredSize(new java.awt.Dimension(110, 35));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnReset.setText("Reset");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setMaximumSize(new java.awt.Dimension(110, 35));
        btnReset.setMinimumSize(new java.awt.Dimension(110, 35));
        btnReset.setPreferredSize(new java.awt.Dimension(110, 35));
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        btnReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnResetKeyPressed(evt);
            }
        });
        jToolBar1.add(btnReset);

        btnFilter.setText("Filter");
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setMaximumSize(new java.awt.Dimension(110, 35));
        btnFilter.setMinimumSize(new java.awt.Dimension(110, 35));
        btnFilter.setPreferredSize(new java.awt.Dimension(110, 35));
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilter);

        jLabel8.setText("Tanggal");

        btnPilihDies.setText("Pilih");
        btnPilihDies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihDiesActionPerformed(evt);
            }
        });
        btnPilihDies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPilihDiesKeyPressed(evt);
            }
        });

        txtNamaDies.setEditable(false);
        txtNamaDies.setToolTipText("Nama Dies");
        txtNamaDies.setFocusable(false);
        txtNamaDies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDiesActionPerformed(evt);
            }
        });

        btnPilihMesin.setText("Pilih");
        btnPilihMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMesinActionPerformed(evt);
            }
        });
        btnPilihMesin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPilihMesinKeyPressed(evt);
            }
        });

        txtNamaMesin.setEditable(false);
        txtNamaMesin.setToolTipText("Nama Mesin");
        txtNamaMesin.setFocusable(false);

        txtProses.setEditable(false);
        txtProses.setToolTipText("Proses dies");
        txtProses.setFocusable(false);

        txtCustomer.setEditable(false);
        txtCustomer.setToolTipText("Nama Customer");
        txtCustomer.setFocusable(false);

        jLabel5.setText("Proses");

        jLabel6.setText("Customer");

        jLabel7.setText("Ka. Shift");

        txtKepala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Operator");

        txtOperator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Mulai");

        txtMulai.setVerifyInputWhenFocusTarget(false);
        txtMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMulaiActionPerformed(evt);
            }
        });
        txtMulai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMulaiKeyTyped(evt);
            }
        });

        txtSelesai.setVerifyInputWhenFocusTarget(false);
        txtSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelesaiActionPerformed(evt);
            }
        });
        txtSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSelesaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSelesaiKeyTyped(evt);
            }
        });

        jLabel11.setText("Selesai");

        txtFilter.setEnabled(false);
        txtFilter.setVerifyInputWhenFocusTarget(false);
        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilterKeyTyped(evt);
            }
        });

        btnPilih.setText("Pilih");
        btnPilih.setEnabled(false);
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        btnTanggalMin.setText("<");
        btnTanggalMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTanggalMin.setFocusPainted(false);
        btnTanggalMin.setFocusable(false);
        btnTanggalMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanggalMinActionPerformed(evt);
            }
        });

        btnAutoNoTrial.setText("Auto");
        btnAutoNoTrial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAutoNoTrial.setFocusPainted(false);
        btnAutoNoTrial.setFocusable(false);
        btnAutoNoTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoNoTrialActionPerformed(evt);
            }
        });

        btnNow.setText("Now");
        btnNow.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNow.setFocusPainted(false);
        btnNow.setFocusable(false);
        btnNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNowActionPerformed(evt);
            }
        });

        btnTanggalPlus.setText(">");
        btnTanggalPlus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTanggalPlus.setFocusPainted(false);
        btnTanggalPlus.setFocusable(false);
        btnTanggalPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanggalPlusActionPerformed(evt);
            }
        });

        txtNoTrial.setText("190");

        btnNoTrialMin.setText("<");
        btnNoTrialMin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNoTrialMin.setFocusPainted(false);
        btnNoTrialMin.setFocusable(false);
        btnNoTrialMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoTrialMinActionPerformed(evt);
            }
        });

        btnNoTrialPlus.setText(">");
        btnNoTrialPlus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNoTrialPlus.setFocusPainted(false);
        btnNoTrialPlus.setFocusable(false);
        btnNoTrialPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoTrialPlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtProses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtCustomer, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKepala, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnPilihMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNamaMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPilihDies, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamaDies, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtNoTrial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNoTrialMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAutoNoTrial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnTanggalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTanggalPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btnNoTrialPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoNoTrial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoTrial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoTrialMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoTrialPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTanggalMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTanggalPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihDies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaDies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPilihMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtKepala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Table"));

        jScrollPane1.setToolTipText("");

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Trial", "Tanggal", "id dies", "Produk", "Proses", "id mesin", "Mesin", "id kepala", "Ka. Shiftl", "id operator", "Operator", "Mulai", "Selesai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableViewMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(0).setMaxWidth(70);
            tableView.getColumnModel().getColumn(1).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(1).setMaxWidth(70);
            tableView.getColumnModel().getColumn(2).setMinWidth(0);
            tableView.getColumnModel().getColumn(2).setPreferredWidth(0);
            tableView.getColumnModel().getColumn(2).setMaxWidth(0);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(4).setMaxWidth(120);
            tableView.getColumnModel().getColumn(5).setMinWidth(0);
            tableView.getColumnModel().getColumn(5).setPreferredWidth(0);
            tableView.getColumnModel().getColumn(5).setMaxWidth(0);
            tableView.getColumnModel().getColumn(6).setPreferredWidth(50);
            tableView.getColumnModel().getColumn(6).setMaxWidth(50);
            tableView.getColumnModel().getColumn(7).setMinWidth(0);
            tableView.getColumnModel().getColumn(7).setPreferredWidth(0);
            tableView.getColumnModel().getColumn(7).setMaxWidth(0);
            tableView.getColumnModel().getColumn(8).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(8).setMaxWidth(120);
            tableView.getColumnModel().getColumn(9).setMinWidth(0);
            tableView.getColumnModel().getColumn(9).setPreferredWidth(0);
            tableView.getColumnModel().getColumn(9).setMaxWidth(0);
            tableView.getColumnModel().getColumn(10).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(10).setMaxWidth(120);
            tableView.getColumnModel().getColumn(11).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(11).setMaxWidth(70);
            tableView.getColumnModel().getColumn(12).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(12).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(320, 35));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(320, 35));

        mnuLaporan.setText("Laporan");

        mniLapTrial.setText("Laporan Trial");
        mniLapTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapTrialActionPerformed(evt);
            }
        });
        mnuLaporan.add(mniLapTrial);
        mnuLaporan.add(jSeparator5);

        jMenuBar1.add(mnuLaporan);

        jMenu1.setText("Tentang");

        mniTentangAplikasi.setText("Tentang Aplikasi");
        mniTentangAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTentangAplikasiActionPerformed(evt);
            }
        });
        jMenu1.add(mniTentangAplikasi);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pilihMesin(Mesin mesin) {
//        txtIdMesin.setText(mesin.getId_mesin().toString());
        setField(mesin);
        this.mesin = mesin;
    }

    private void mniTentangAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTentangAplikasiActionPerformed
        try {
            TentangAplikasi view = new TentangAplikasi(this , true);
            view.setTitle("Laporan trial Produksi");
            view.setResizable(false);
            view.setLocationByPlatform(true);
            view.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniTentangAplikasiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
        refreshDataTables();
        ambilNoTrialTertinggi();
        setDateNowMinOne();
        txtNoTrial.setEditable(true);
        btnNoTrialMin.setVisible(true);
        btnAutoNoTrial.setVisible(true);
        btnNoTrialPlus.setVisible(true);
        btnSimpan.setText("Simpan");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (btnSimpan.getText().equals("Simpan")) {
            try {
                String depanMulai = txtMulai.getText(0, 2);
                String belakangMulai = txtMulai.getText(2, 2);
                StringBuilder m = new StringBuilder().append(depanMulai).append(":").append(belakangMulai).append(":00");

                String depanSelesai = txtSelesai.getText(0, 2);
                String belakangSelesai = txtSelesai.getText(2, 2);
                String s = depanSelesai + ":" + belakangSelesai + ":00";

                trial.setId_trial(Integer.valueOf(txtNoTrial.getText()));
                trial.setTanggal(Date.valueOf(ValueFormatter.getDateSQL(txtTanggal.getDate())));
                trial.setDies(dies);
                trial.setMesin(mesin);
                trial.setKepala(daftarKepala.get(txtKepala.getSelectedIndex()));
                trial.setOperator(daftarOperator.get(txtOperator.getSelectedIndex()));
                trial.setMulai(Time.valueOf(m.toString()));
                trial.setSelesai(Time.valueOf(s));

                repoTrial.save(trial);
                refreshDataTables();
                clearFields();
                selectLastRow();
            } catch (BadLocationException ex) {
                JOptionPane.showMessageDialog(this, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String depanMulai = txtMulai.getText(0, 2);
                String belakangMulai = txtMulai.getText(2, 2);
                StringBuilder m = new StringBuilder().append(depanMulai).append(":").append(belakangMulai).append(":00");

                String depanSelesai = txtSelesai.getText(0, 2);
                String belakangSelesai = txtSelesai.getText(2, 2);
                String s = depanSelesai + ":" + belakangSelesai + ":00";

                trial.setId_trial(Integer.valueOf(txtNoTrial.getText()));
                trial.setTanggal(Date.valueOf(ValueFormatter.getDateSQL(txtTanggal.getDate())));
                trial.setDies(dies);
                trial.setMesin(mesin);
                trial.setKepala(daftarKepala.get(txtKepala.getSelectedIndex()));
                trial.setOperator(daftarOperator.get(txtOperator.getSelectedIndex()));
                trial.setMulai(Time.valueOf(m.toString()));
                trial.setSelesai(Time.valueOf(s));
                repoTrial.update(trial);
                btnSimpan.setText("Simpan");
                refreshDataTables();
                btnResetActionPerformed(evt);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadLocationException ex) {
                JOptionPane.showMessageDialog(this, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnSimpanActionPerformed
    public void selectLastRow() {
        tableView.setRowSelectionInterval(tableView.getRowCount() - 1, tableView.getRowCount() - 1);
        tableView.scrollRectToVisible(new Rectangle(tableView.getCellRect(tableView.getRowCount() - 1, 0, true)));
    }
    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        refreshDataTables();
//        txtFilter.setEnabled(true);
//        btnPilih.setEnabled(true);
    }//GEN-LAST:event_btnFilterActionPerformed

    private void btnPilihDiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihDiesActionPerformed
        DetailDiesView view = new DetailDiesView(this, this, true);
        view.setLocationRelativeTo(null);
        view.setResizable(false);
        view.setVisible(true);
    }//GEN-LAST:event_btnPilihDiesActionPerformed

    private void btnPilihMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMesinActionPerformed
        DetailMesinView view = new DetailMesinView(this, this, true);
        view.setLocationRelativeTo(null);
        view.setResizable(false);
        view.setVisible(true);
    }//GEN-LAST:event_btnPilihMesinActionPerformed

    private void txtNamaDiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDiesActionPerformed

    private void txtMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMulaiActionPerformed

    private void txtSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelesaiActionPerformed

    private void txtSelesaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelesaiKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtSelesaiKeyTyped

    private void txtMulaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMulaiKeyTyped
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }

    }//GEN-LAST:event_txtMulaiKeyTyped

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed

    private void txtFilterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterKeyTyped

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed

    }//GEN-LAST:event_btnPilihActionPerformed

    private void txtSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSelesaiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_txtSelesaiKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnPilihDiesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPilihDiesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPilihDiesActionPerformed(null);
        }
    }//GEN-LAST:event_btnPilihDiesKeyPressed

    private void btnPilihMesinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPilihMesinKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPilihMesinActionPerformed(null);
        }

    }//GEN-LAST:event_btnPilihMesinKeyPressed

    private void btnResetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnResetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnResetActionPerformed(null);
        }
    }//GEN-LAST:event_btnResetKeyPressed

    private void btnTanggalMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanggalMinActionPerformed
        date = date.minusDays(1);
        this.txtTanggal.setDate(Date.valueOf(date.toString()));
    }//GEN-LAST:event_btnTanggalMinActionPerformed

    private void btnAutoNoTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoNoTrialActionPerformed
        ambilNoTrialTertinggi();
    }//GEN-LAST:event_btnAutoNoTrialActionPerformed

    private void ambilNoTrialTertinggi() {
        try {
            List<Trial> list = repoTrial.findMaxValue();
            if (!list.isEmpty()) {
                for (Trial trial : list) {
                    no = trial.getId_trial() + 1;
                }
                txtNoTrial.setText(String.valueOf(no));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan kode!", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    private void btnNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNowActionPerformed
        date = LocalDate.now();
        this.txtTanggal.setDate(Date.valueOf(date.toString()));
    }//GEN-LAST:event_btnNowActionPerformed

    private void btnTanggalPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanggalPlusActionPerformed
        date = date.plusDays(1);
        this.txtTanggal.setDate(Date.valueOf(date.toString()));
    }//GEN-LAST:event_btnTanggalPlusActionPerformed

    private void btnNoTrialMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoTrialMinActionPerformed
        no = no - 1;
        txtNoTrial.setText(String.valueOf(no));
    }//GEN-LAST:event_btnNoTrialMinActionPerformed

    private void btnNoTrialPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoTrialPlusActionPerformed
        no = no + 1;
        txtNoTrial.setText(String.valueOf(no));
    }//GEN-LAST:event_btnNoTrialPlusActionPerformed

    private void mniLapTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapTrialActionPerformed
        try {
            LapTrial view = new LapTrial(this, true);
            view.setTitle("Laporan trial Produksi");
            view.setResizable(true);
            view.setLocationByPlatform(true);
            view.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLapTrialActionPerformed

    private void pmnuUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmnuUbahActionPerformed
        setFieldsUntukUbah();
    }//GEN-LAST:event_pmnuUbahActionPerformed

    private void tableViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseReleased
        if (evt.isPopupTrigger()) {
            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());
            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableViewMouseReleased
    private void setFieldsUntukUbah() {
        if (tableController.isSelected()) {
            trial = daftarTrial.get(tableController.getRowSelected());
            txtNoTrial.setText(trial.getId_trial().toString());
            txtNoTrial.setEditable(false);
            btnNoTrialMin.setVisible(false);
            btnAutoNoTrial.setVisible(false);
            btnNoTrialPlus.setVisible(false);
            dies = trial.getDies();
            mesin = trial.getMesin();
            kepala = trial.getKepala();
            operator = trial.getOperator();

            txtTanggal.setDate(trial.getTanggal());
            txtNamaDies.setText(trial.getDies().getNama());
            txtProses.setText(trial.getDies().getProses());
            txtCustomer.setText(trial.getDies().getCustomer());
            txtNamaMesin.setText(trial.getMesin().getNama());
            txtKepala.setSelectedItem(trial.getKepala().getNama());
            txtOperator.setSelectedItem(trial.getOperator().getNama());
            txtMulai.setText(trial.getMulai().toString());
            String a, b, c, d, e, f, g, h;
            a = trial.getMulai().toString();
            b = a.substring(0, 2);
            c = a.substring(3, 5);
            d = b + c;
            txtMulai.setText(d);
            e = trial.getSelesai().toString();
            f = e.substring(0, 2);
            g = e.substring(3, 5);
            h = f + g;
            txtSelesai.setText(h);
            btnSimpan.setText("Update");

        } else {
            JOptionPane.showMessageDialog(this, "Data Aset belum dipilih!", getTitle(), JOptionPane.WARNING_MESSAGE);
        }
    }

    private void textFieldLimit() {
        txtMulai.setDocument(new FieldLimit(4));
        txtSelesai.setDocument(new FieldLimit(4));
    }

    public void refreshDataTables() {
        try {
            tableController.clearData();
            this.daftarTrial = repoTrial.findAll();
            for (Trial trial : daftarTrial) {
                Object[] row = {trial.getId_trial(), ValueFormatter.getLocalDateShort(trial.getTanggal().toLocalDate()), trial.getDies().getId_dies(), trial.getDies().getNama(), trial.getDies().getProses(),
                    trial.getMesin().getId_mesin(), trial.getMesin().getNama(),
                    trial.getKepala().getId_kepala(), trial.getKepala().getNama(),
                    trial.getOperator().getId_operator(), trial.getOperator().getNama(),
                    trial.getMulai(), trial.getSelesai()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan data trial", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoNoTrial;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnNoTrialMin;
    private javax.swing.JButton btnNoTrialPlus;
    private javax.swing.JButton btnNow;
    private javax.swing.JButton btnPilih;
    private javax.swing.JButton btnPilihDies;
    private javax.swing.JButton btnPilihMesin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTanggalMin;
    private javax.swing.JButton btnTanggalPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mniLapTrial;
    private javax.swing.JMenuItem mniTentangAplikasi;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenuItem pmnuUbah;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtFilter;
    private javax.swing.JComboBox txtKepala;
    private javax.swing.JTextField txtMulai;
    private javax.swing.JTextField txtNamaDies;
    private javax.swing.JTextField txtNamaMesin;
    private javax.swing.JTextField txtNoTrial;
    private javax.swing.JComboBox txtOperator;
    private javax.swing.JTextField txtProses;
    private javax.swing.JTextField txtSelesai;
    private com.toedter.calendar.JDateChooser txtTanggal;
    // End of variables declaration//GEN-END:variables

    private void setField(Mesin mesin) {
        txtNamaMesin.setText(mesin.getNama());

    }

    public void pilihDies(Dies dies) {
        txtNamaDies.setText(dies.getNama());
        txtProses.setText(dies.getProses());
        txtCustomer.setText(dies.getCustomer());
        this.dies = dies;
    }
}
