/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.laporan;

import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.Mesin;
import aplikasi.entity.Trial;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import repository.RepoMesin;
import repository.RepoTrial;
import services.ServiceMesin;
import services.ServiceTrial;
import view.MainMenu;

/**
 *
 * @author soraya
 */
public class LapTrial extends javax.swing.JDialog {

    private final RepoMesin repoMesin;
    private final RepoTrial repoTrial;
    private final TableViewController tableController;

    private List<Trial> daftarTrial = new ArrayList<>();
    private List<Mesin> daftarMesin = new ArrayList<>();

    public LapTrial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.repoMesin = new ServiceMesin(KoneksiDB.getDataSource());
        this.repoTrial = new ServiceTrial(KoneksiDB.getDataSource());
        this.tableController = new TableViewController(tableView);
        setFirstDayInMonth();
        txtTanggalAkhir.setDate(new java.util.Date());
        refresDaftarMesin();
        refreshDataTrial();
        hideFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        txtTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTanggalAkhir = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFilter = new javax.swing.JButton();
        lblProduk = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        lblProses = new javax.swing.JLabel();
        txtProses = new javax.swing.JTextField();
        lblMesin = new javax.swing.JLabel();
        txtMesin = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(721, 52));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jLabel1.setText(" Tanggal : ");
        jToolBar1.add(jLabel1);

        txtTanggalAwal.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAwal);

        jLabel2.setText("s/d");
        jToolBar1.add(jLabel2);

        txtTanggalAkhir.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAkhir);

        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 5));
        jSeparator1.setSeparatorSize(new java.awt.Dimension(5, 5));
        jToolBar1.add(jSeparator1);

        btnFilter.setText(">>");
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilter);

        lblProduk.setText("Produk : ");
        jToolBar1.add(lblProduk);

        txtProduk.setMaximumSize(new java.awt.Dimension(120, 29));
        txtProduk.setMinimumSize(new java.awt.Dimension(120, 29));
        txtProduk.setPreferredSize(new java.awt.Dimension(120, 29));
        txtProduk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProdukCaretUpdate(evt);
            }
        });
        jToolBar1.add(txtProduk);

        lblProses.setText(" Proses : ");
        jToolBar1.add(lblProses);

        txtProses.setMaximumSize(new java.awt.Dimension(100, 29));
        txtProses.setMinimumSize(new java.awt.Dimension(100, 29));
        txtProses.setPreferredSize(new java.awt.Dimension(100, 29));
        txtProses.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtProsesCaretUpdate(evt);
            }
        });
        jToolBar1.add(txtProses);

        lblMesin.setText(" Mesin : ");
        jToolBar1.add(lblMesin);

        txtMesin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMesin.setToolTipText("");
        txtMesin.setMaximumSize(new java.awt.Dimension(90, 29));
        txtMesin.setMinimumSize(new java.awt.Dimension(90, 29));
        txtMesin.setPreferredSize(new java.awt.Dimension(90, 29));
        txtMesin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMesinMouseReleased(evt);
            }
        });
        txtMesin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMesinKeyReleased(evt);
            }
        });
        jToolBar1.add(txtMesin);

        jLabel3.setText("  ");
        jToolBar1.add(jLabel3);

        btnProses.setText("Proses");
        btnProses.setFocusable(false);
        btnProses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProses.setMaximumSize(new java.awt.Dimension(100, 29));
        btnProses.setMinimumSize(new java.awt.Dimension(100, 29));
        btnProses.setPreferredSize(new java.awt.Dimension(100, 29));
        btnProses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProses);

        btnCetak.setText("Cetak");
        btnCetak.setEnabled(false);
        btnCetak.setFocusable(false);
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCetak.setMaximumSize(new java.awt.Dimension(100, 29));
        btnCetak.setMinimumSize(new java.awt.Dimension(100, 29));
        btnCetak.setPreferredSize(new java.awt.Dimension(100, 29));
        btnCetak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCetak);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToolBar1.add(lblTotal);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Peminjaman Aset"));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Trial", "Tanggal", "Produk", "Proses", "Mesin", "Ka Shift", "Operator", "Mulai", "Selesai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(0).setMaxWidth(70);
            tableView.getColumnModel().getColumn(1).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(1).setMaxWidth(70);
            tableView.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(3).setMaxWidth(120);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableView.getColumnModel().getColumn(4).setMaxWidth(50);
            tableView.getColumnModel().getColumn(5).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(5).setMaxWidth(120);
            tableView.getColumnModel().getColumn(6).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(6).setMaxWidth(120);
            tableView.getColumnModel().getColumn(7).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(7).setMaxWidth(70);
            tableView.getColumnModel().getColumn(8).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(8).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        if (btnFilter.getText().equals(">>")) {
            btnFilter.setText("<<");
            showFilter();
        } else {
            btnFilter.setText(">>");
            txtProduk.setText("");
            txtProses.setText("");
            txtMesin.setSelectedIndex(0);
            refreshDataTrial();
            hideFilter();
        }
    }//GEN-LAST:event_btnFilterActionPerformed
    private void setFirstDayInMonth() {
        LocalDate todaydate = LocalDate.now();
        txtTanggalAwal.setDate(Date.valueOf(todaydate.withDayOfMonth(1).toString()));

    }

    private void hideFilter() {
        lblProduk.setVisible(false);
        txtProduk.setVisible(false);
        lblProses.setVisible(false);
        txtProses.setVisible(false);
        lblMesin.setVisible(false);
        txtMesin.setVisible(false);
        btnProses.setVisible(true);
    }

    private void showFilter() {
        lblProduk.setVisible(true);
        txtProduk.setVisible(true);
        lblProses.setVisible(true);
        txtProses.setVisible(true);
        lblMesin.setVisible(true);
        txtMesin.setVisible(true);
        btnProses.setVisible(false);
    }

    public void refreshDataTables() {
        try {
            tableController.clearData();
            this.daftarTrial = repoTrial.findAll();
            for (Trial trial : daftarTrial) {
                Object[] row = {trial.getId_trial(), ValueFormatter.getLocalDateShort(trial.getTanggal().toLocalDate()), trial.getDies().getNama(), trial.getDies().getProses(),
                    trial.getMesin().getNama(), trial.getKepala().getNama(), trial.getOperator().getNama(), trial.getMulai(), trial.getSelesai()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 1, 3, 4, 5, 6, 7, 8));
            lblTotal.setText(repoTrial.countTrials().toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan data trial", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refresDaftarMesin() {
        try {
            txtMesin.removeAllItems();
            txtMesin.addItem("%");
            daftarMesin = repoMesin.findAll();
            for (Mesin k : daftarMesin) {
                txtMesin.addItem(k.getNama());
            }
            txtMesin.setSelectedItem("%");
        } catch (SQLException ex) {
            Logger.getLogger(LapTrial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        refreshDataTrial();
    }//GEN-LAST:event_btnProsesActionPerformed
    private void refreshDataTrial() {
        try {
         String valueTglAwal = ValueFormatter.getDateSQL(txtTanggalAwal.getDate());
         String valueTglAkhir = ValueFormatter.getDateSQL(txtTanggalAkhir.getDate());
            tableController.clearData();
            daftarTrial = repoTrial.findTrialByProdukBymesin(Date.valueOf(valueTglAwal),Date.valueOf(valueTglAkhir) , txtProduk.getText(), txtProses.getText(), txtMesin.getSelectedItem().toString());
//            if (daftarTrial.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Tidak ada transaksi !", getTitle(), JOptionPane.INFORMATION_MESSAGE);
//            }
            btnCetak.setEnabled(!daftarTrial.isEmpty());
            for (Trial t : daftarTrial) {
                Object[] row = {t.getId_trial(), ValueFormatter.getLocalDateShort(t.getTanggal().toLocalDate()), t.getDies().getNama(), t.getDies().getProses(), t.getMesin().getNama(),
                    t.getKepala().getNama(), t.getOperator().getNama(), t.getMulai(), t.getSelesai()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 1, 3, 4, 5, 6, 7, 8));
            lblTotal.setText("  "+daftarTrial.size());
        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan data Trial", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LapTrial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        if (daftarTrial.size() > 0) {
            try {
                String url = "/laporan/LaporanTrial.jasper";
                Map<String, Object> map = new HashMap<>();
                map.put("tglAwal", txtTanggalAwal.getDate());
                map.put("tglAkhir", txtTanggalAkhir.getDate());
                JasperPrint print = JasperFillManager.fillReport(
                        getClass().getResourceAsStream(url),
                        map,
                        new JRBeanCollectionDataSource(daftarTrial));
                JasperViewer view = new JasperViewer(print, false);
                view.setLocationRelativeTo(null);
                view.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
                view.setAlwaysOnTop(true);
                view.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(LapTrial.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data belum diproses", getTitle(), JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtProdukCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProdukCaretUpdate
        refreshDataTrial();
    }//GEN-LAST:event_txtProdukCaretUpdate

    private void txtProsesCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtProsesCaretUpdate
        refreshDataTrial();
    }//GEN-LAST:event_txtProsesCaretUpdate

    private void txtMesinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMesinKeyReleased
        refreshDataTrial();
    }//GEN-LAST:event_txtMesinKeyReleased

    private void txtMesinMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesinMouseReleased
    }//GEN-LAST:event_txtMesinMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblMesin;
    private javax.swing.JLabel lblProduk;
    private javax.swing.JLabel lblProses;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tableView;
    private javax.swing.JComboBox<String> txtMesin;
    private javax.swing.JTextField txtProduk;
    private javax.swing.JTextField txtProses;
    private com.toedter.calendar.JDateChooser txtTanggalAkhir;
    private com.toedter.calendar.JDateChooser txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
