/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.laporan;

import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.Mesin;
import aplikasi.entity.Trial;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import repository.RepoMesin;
import repository.RepoTrial;
import services.ServiceMesin;
import services.ServiceTrial;
import view.MainMenu;

/**
 *
 * @author soraya
 */
public class LapTrial extends javax.swing.JDialog {

private final RepoMesin repoMesin;    
private final RepoTrial repoTrial;  
private final TableViewController tableController;

private List<Trial> daftarTrial = new ArrayList<>();
private List<Mesin> daftarMesin = new ArrayList<>();



    public LapTrial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.repoMesin = new ServiceMesin(KoneksiDB.getDataSource());
        this.repoTrial = new ServiceTrial(KoneksiDB.getDataSource());
        this.tableController = new TableViewController(tableView);
        refresDaftarMesin();
        refreshDataTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        txtTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTanggalAkhir = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFilter = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        txtProduk = new javax.swing.JTextField();
        lblKepemilikan = new javax.swing.JLabel();
        txtMesin = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(721, 52));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jLabel1.setText(" Tanggal : ");
        jToolBar1.add(jLabel1);

        txtTanggalAwal.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAwal);

        jLabel2.setText("s/d");
        jToolBar1.add(jLabel2);

        txtTanggalAkhir.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAkhir);

        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 5));
        jSeparator1.setSeparatorSize(new java.awt.Dimension(5, 5));
        jToolBar1.add(jSeparator1);

        btnFilter.setText(">>");
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilter);

        lblKategori.setText("Produk : ");
        jToolBar1.add(lblKategori);

        txtProduk.setMaximumSize(new java.awt.Dimension(150, 29));
        txtProduk.setMinimumSize(new java.awt.Dimension(150, 29));
        txtProduk.setPreferredSize(new java.awt.Dimension(150, 29));
        jToolBar1.add(txtProduk);

        lblKepemilikan.setText(" Mesin : ");
        jToolBar1.add(lblKepemilikan);

        txtMesin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMesin.setToolTipText("");
        txtMesin.setMaximumSize(new java.awt.Dimension(90, 29));
        txtMesin.setMinimumSize(new java.awt.Dimension(90, 29));
        txtMesin.setPreferredSize(new java.awt.Dimension(90, 29));
        txtMesin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtMesinItemStateChanged(evt);
            }
        });
        jToolBar1.add(txtMesin);

        jLabel3.setText("  ");
        jToolBar1.add(jLabel3);

        btnProses.setText("Proses");
        btnProses.setFocusable(false);
        btnProses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProses.setMaximumSize(new java.awt.Dimension(100, 29));
        btnProses.setMinimumSize(new java.awt.Dimension(100, 29));
        btnProses.setPreferredSize(new java.awt.Dimension(100, 29));
        btnProses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProses);

        btnCetak.setText("Cetak");
        btnCetak.setEnabled(false);
        btnCetak.setFocusable(false);
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCetak.setMaximumSize(new java.awt.Dimension(100, 29));
        btnCetak.setMinimumSize(new java.awt.Dimension(100, 29));
        btnCetak.setPreferredSize(new java.awt.Dimension(100, 29));
        btnCetak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCetak);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Peminjaman Aset"));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Trial", "Tanggal", "Produk", "Proses", "Mesin", "Ka Shift", "Operator", "Mulai", "Selesai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(0).setMaxWidth(70);
            tableView.getColumnModel().getColumn(1).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(1).setMaxWidth(70);
            tableView.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(3).setMaxWidth(120);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableView.getColumnModel().getColumn(4).setMaxWidth(50);
            tableView.getColumnModel().getColumn(5).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(5).setMaxWidth(120);
            tableView.getColumnModel().getColumn(6).setPreferredWidth(120);
            tableView.getColumnModel().getColumn(6).setMaxWidth(120);
            tableView.getColumnModel().getColumn(7).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(7).setMaxWidth(70);
            tableView.getColumnModel().getColumn(8).setPreferredWidth(70);
            tableView.getColumnModel().getColumn(8).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
                if (btnFilter.getText().equals(">>")) {
                        btnFilter.setText("<<");
                        showFilter();
                    } else {
                        btnFilter.setText(">>");
                        txtProduk.setText("");
                        txtMesin.setSelectedIndex(0);
                        hideFilter();
                    }
    }//GEN-LAST:event_btnFilterActionPerformed
private void hideFilter() {
        lblKategori.setVisible(false);
        txtProduk.setVisible(false);
        lblKepemilikan.setVisible(false);
        txtMesin.setVisible(false);
    }

    private void showFilter() {
        lblKategori.setVisible(true);
        txtProduk.setVisible(true);
        lblKepemilikan.setVisible(true);
        txtMesin.setVisible(true);
    }
    public void refreshDataTables() {
        try {
            tableController.clearData();
            this.daftarTrial = repoTrial.findAll();
            for (Trial trial : daftarTrial) {
                Object[] row = {trial.getId_trial(), ValueFormatter.getLocalDateShort(trial.getTanggal().toLocalDate()), trial.getDies().getNama(), trial.getDies().getProses(),
                    trial.getMesin().getNama(), trial.getKepala().getNama(), trial.getOperator().getNama(), trial.getMulai(), trial.getSelesai()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 1, 3, 4, 5, 6, 7, 8));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan data trial", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void refresDaftarMesin() {
        try {
            txtMesin.removeAllItems();
            daftarMesin = repoMesin.findAll();
            for (Mesin k : daftarMesin) {
                txtMesin.addItem(k.getNama());
            }
        } catch (SQLException ex) {
            Logger.getLogger(LapTrial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtMesinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtMesinItemStateChanged
        //        refreshDataTablesWithFilter();
    }//GEN-LAST:event_txtMesinItemStateChanged

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
//        String valueTglAwal = ValueFormatter.getDateSQL(txtTanggalAwal.getDate());
//        String valueTglAkhir = ValueFormatter.getDateSQL(txtTanggalAkhir.getDate());
//        refreshDataPeminjaman(Date.valueOf(valueTglAwal), Date.valueOf(valueTglAkhir));
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        //        if (daftarPeminjamanDetail.size() > 0) {
            //            try {
                //                String url = "/laporan/PeminjamanAset.jasper";
                //                Map<String, Object> map = new HashMap<>();
                //                map.put("tglAwal", txtTanggalAwal.getDate());
                //                map.put("tglAkhir", txtTanggalAkhir.getDate());
                //                map.put("pengguna", p.getNama());
                //                map.put("jabatan", p.getJabatan().toString());
                //                JasperPrint print = JasperFillManager.fillReport(
                    //                        getClass().getResourceAsStream(url),
                    //                        map,
                    //                        new JRBeanCollectionDataSource(daftarPeminjamanDetail));
                //                JasperViewer view = new JasperViewer(print, false);
                //                view.setLocationRelativeTo(null);
                //                view.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
                //                view.setVisible(true);
                //            } catch (JRException ex) {
                //                Logger.getLogger(LaporanSirkulasiAsetView.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //        } else {
            //            JOptionPane.showMessageDialog(this, "Data belum diproses", getTitle(), JOptionPane.INFORMATION_MESSAGE);
            //        }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKepemilikan;
    private javax.swing.JTable tableView;
    private javax.swing.JComboBox<String> txtMesin;
    private javax.swing.JTextField txtProduk;
    private com.toedter.calendar.JDateChooser txtTanggalAkhir;
    private com.toedter.calendar.JDateChooser txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
